# Generated by Django 3.1.5 on 2021-04-28 05:02

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0018_auto_20210120_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='details',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
