# Generated by Django 3.1.5 on 2021-04-28 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0019_auto_20210428_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='updated_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
